segprivado/nucleo/urls.py
from django.urls import path
from nucleo import views

app_name = "nucleo"

urlpatterns = [
    
    path('home', views.home, name= "home"),

    path('medicamento/', views.medicamento, name="indexMedicamento"),
    path('medicamento/create/', views.medicamentoCreate.as_view(), name="crearMedicamento"),
    path('medicamento/update/<int:pk>/', views.medicamentoUpdate.as_view(), name="actualizarMedicamento"),
    path('medicamento/delete/<int:pk>/', views.medicamentoDelete, name="eliminarMedicamento"),

    path('especialidad/', views.medicosEspecilidad.as_view(), name="especialidad"),

    path('cita/', views.createCita.as_view(), name="pedirCita"),
    path('cita/indexM/', views.citasActual, name="indexMCita"),
    path('cita/update/<int:pk>/', views.citaTratamiento.as_view(), name="actualizarCita"),
    path('cita/index/', views.verCitas, name="indexCita"),
    path('cita/filter/', views.citasFilter.as_view(), name="filterCita"),
    path('cita/historialM/', views.verCitasMedico, name="historialMCita"),
    path('cita/filterP/', views.filterPaciente.as_view(), name="filterPaciente"),

    path('compra/', views.createCompra.as_view(), name="pedirCompra"),
    path('compra/add/<int:pk>/', views.createCompra.addMedicamento, name="addMedicamento"),

    path('api/login/', views.loginAPI.as_view(), name="loginAPI"),
    path('api/medicos/', views.medicos_APIView.as_view(), name="medicosAPI"),
    path('api/citas/', views.historialCitas_APIView.as_view(), name="citasAPI"),
]

segprivado/segprivado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from registration.views import Login, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    path('',include('nucleo.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
    path('home', TemplateView.as_view(template_name='nucleo/home.html'), name='home'),
    path('acounts/', include('registration.urls')),
]

segprivado/nucleo/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
    MedicodeFamilia= 'MF'
    Digestivo= 'DG'
    Neurologo= 'NE'
    Dermatologo= 'DT'
    Traumatologo= 'TR'
    SinEspecialidad= 'SE'
    ESPECIALIDAD_CHOICES = [(MedicodeFamilia, 'Medico de Familia'),(Digestivo, 'Digestivo'),(Neurologo, 'Neurologo'),(Dermatologo, 'Dermatologo'),(Traumatologo, 'Traumatologo'),(SinEspecialidad, 'Sin Especialidad')]
    first_name = models.CharField(max_length=30, verbose_name="Nombre", null=True)
    last_name = models.CharField(max_length=30, verbose_name="Apellidos", null=True)
    edad = models.IntegerField(null=True)
    date_joined = models.DateTimeField(verbose_name="Fecha de alta", null=True)
    especialidad = models.CharField(max_length=2, choices=ESPECIALIDAD_CHOICES, default=SinEspecialidad)
    username = models.CharField(max_length=30, unique=True, verbose_name="Usuario", null=True)
    password = models.CharField(max_length=100, verbose_name="Contraseña", null=True)
    is_active = models.BooleanField(verbose_name="Activo", default=False)
    is_paciente = models.BooleanField('paciente status',null=True)
    is_medico = models.BooleanField('medico status',null=True)
    direccion = models.CharField(max_length=100, null=True)
    foto = models.ImageField(upload_to='fotos/', null=True)

    def __str__(self):
        if self.first_name is not None or self.last_name is not None:
            return self.first_name + " " + self.last_name
        return self.username
    
    
class Cita(models.Model):
    fecha = models.DateField(null=True)
    observaciones = models.TextField(max_length=200, null=True)
    idMedico = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='medico')
    idPaciente = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='paciente')
    
    class Meta:
        ordering = ('fecha',)

class Medicamento(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)
    receta = models.CharField(max_length=1, null=True)
    precio = models.FloatField(null=True)
    stock = models.IntegerField(null=True)
    
class Compra(models.Model):
    fecha = models.DateField(null=True)
    idPaciente = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True)
    precio = models.FloatField(null=True)
    
class Compra_medicamento(models.Model):
    idCompra = models.ForeignKey(Compra, on_delete=models.CASCADE, null=True)
    idMedicamento = models.ForeignKey(Medicamento, on_delete=models.CASCADE, null=True)
    cant = models.IntegerField(null=True)

segprivado/nucleo/forms.py
from cProfile import label
from datetime import datetime
from faulthandler import disable
from nucleo.models import *
from django import forms

class medicamentoForm(forms.ModelForm):
    class Meta:
        model = Medicamento
        fields = ['nombre', 'descripcion', 'receta', 'precio', 'stock']
        labels = {'nombre':'Nombre', 'descripcion':'Descripcion', 'receta':'Receta', 'precio':'Precio', 'stock':'Stock'}
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}), 
            'descripcion': forms.Textarea(attrs={'class':'form-control'}), 
            'receta': forms.TextInput(attrs={'class':'form-control'}), 
            'precio': forms.NumberInput(attrs={'class':'form-control'}), 
            'stock': forms.NumberInput(attrs={'class':'form-control'})
            }

class citaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(citaForm, self).__init__(*args, **kwargs)
        self.fields['idMedico'].queryset = Usuario.objects.filter(is_medico=True)
        
    class Meta:
        model = Cita
        fields = ['fecha', 'idMedico',]
        labels = {'fecha':'Fecha', 'idMedico':'Medico'}
        
        
        widgets = { 
            'fecha': forms.DateInput(attrs={'type':'date'}),
            
        }

    def clean_fecha(self):
        fecha = self.cleaned_data['fecha']
        if fecha < datetime.date(datetime.now()):
            raise forms.ValidationError("La fecha debe ser mayor o igual a la actual")
        return fecha

    def clean_dis(self):
        fecha = self.cleaned_data['fecha']
        idMedico = self.cleaned_data['idMedico']
        if Cita.objects.filter(fecha=fecha, idMedico=idMedico).count() > 3:
            raise forms.ValidationError("Ese medico no esta disponible en esa fecha")
        return fecha

class citaFormTratamiento(forms.ModelForm):
    class Meta:
        model = Cita
        fields = ['observaciones',]
        labels = {'observaciones':'Observaciones'}
        widgets = { 
            'observaciones': forms.Textarea(attrs={'class':'form-control'}),
            
        }

class compraForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(compraForm, self).__init__(*args, **kwargs)
        

    class Meta:
        model = Compra
        fields = ['fecha','precio']
        labels = {'fecha':'Fecha', 'idPaciente':'Paciente', 'precio':'Total'}
        widgets = {
            'fecha': forms.DateInput(attrs={
                'disabled': True,
                'value':datetime.date(datetime.now())
                }),
            'precio': forms.NumberInput(attrs={
                'disabled': True,
                'value':0.0}),
        }

segprivado/nucleo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from nucleo.models import Usuario
from nucleo.forms import *
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from nucleo.decorators import *
from nucleo.serializers import citaSerializer, medicoSerializer
from .carrito import Carrito

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import ParseError
from rest_framework import serializers, status
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
# Create your views here.

@login_required
def home(request):
    medico=Usuario.objects.filter(is_medico=True)
    
    
    context={'medicos':medico,
 }
    return render(request, 'nucleo/home.html')

@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class medicamentoCreate(CreateView):
      model = Medicamento
      form_class = medicamentoForm
      template_name = 'nucleo/medicamentos/create.html'
      success_url = reverse_lazy('nucleo:indexMedicamento')

      def post(self, request, *args, **kwargs):
         self.object = self.get_object
         form = self.form_class(request.POST)
         if form.is_valid():
            medicamento = form.save(commit=False)
            medicamento.save()
            messages.success(request, 'Medicamento creado correctamente')
            return HttpResponseRedirect(reverse('nucleo:indexMedicamento'))
         else:
            return self.render_to_response(self.get_context_data(form=form))

@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class medicamentoUpdate(UpdateView):
      model = Medicamento
      form_class = medicamentoForm
      template_name = 'nucleo/medicamentos/create.html'
      success_url = reverse_lazy('nucleo:indexMedicamento')

@login_required
@staff_member_required
def medicamentoDelete(request, pk):
   medicamento = get_object_or_404(Medicamento, id=pk)
   medicamento.delete()
   messages.success(request, 'Medicamento eliminado correctamente')
   return redirect('nucleo:indexMedicamento')

@login_required
@staff_member_required
def medicamento(request):
   medicamentos = Medicamento.objects.all()
   context = {'medicamentos': medicamentos}
   return render(request, 'nucleo/medicamentos/index.html', context)

class medicosEspecilidad(ListView):
   model = Usuario
   template_name = 'nucleo/especialidad.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      especialidadGet = self.request.GET.get('especialidad')
      
      if(self.request.GET.get('especialidad')!=0):
         data = Usuario.objects.filter(especialidad=especialidadGet, is_medico=True)
      else:
         data = Usuario.objects.filter(is_medico=True)
      
      context['data'] = data
      return context

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class createCita(CreateView):
   model = Cita
   form_class = citaForm
   template_name = 'nucleo/cita/create.html'
   success_url = reverse_lazy('nucleo:home')

   def post(self, request, *args, **kwargs):
      self.object = self.get_object
      form = self.form_class(request.POST)
      if form.is_valid():
         cita = form.save(commit=False)
         cita.idPaciente = self.request.user
         cita.idMedico = form.cleaned_data['idMedico']
         cita.save()
         messages.success(request, 'Cita creada correctamente')
         return HttpResponseRedirect(reverse('nucleo:home'))
      else:
         return self.render_to_response(self.get_context_data(form=form))
   
   def dispatch(self, request, *args, **kwargs):
         return super().dispatch(request, *args, **kwargs)

@login_required
@medico
def citasActual(request):
   citas = Cita.objects.filter(fecha__gte=datetime.date(datetime.now()), idMedico=request.user.id)
   context = {'citas': citas}
   return render(request, 'nucleo/cita/indexM.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(medico, name='dispatch')
class citaTratamiento(UpdateView):
   model = Cita
   form_class = citaFormTratamiento
   template_name = 'nucleo/cita/update.html'
   success_url = reverse_lazy('nucleo:actualizarCita')

@login_required
@paciente
def verCitas(request):
   if(request.user.is_paciente):
      citas = Cita.objects.filter(idPaciente=request.user.id)
   context = {'citas': citas}
   return render(request, 'nucleo/cita/indexP.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class citasFilter(ListView):
   model = Cita
   template_name = 'nucleo/cita/indexP.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      fechaIni = self.request.GET.get('fechaIni', None)
      fechaFin = self.request.GET.get('fechaFin', None)
      if fechaIni != '' and fechaFin != '':
         citas = Cita.objects.filter(idPaciente=self.request.user.id, fecha__range=(fechaIni, fechaFin)).filter(fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      else:
         citas = Cita.objects.filter(idPaciente=self.request.user.id).filter(fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      context['citas'] = citas
      return context

@login_required
@medico
def verCitasMedico(request):
   if(request.user.is_medico):
      citas = Cita.objects.filter(idMedico=request.user.id, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      paciente = citas.values_list('idPaciente', flat=True).distinct()
      pacientes = Usuario.objects.filter(id__in=paciente)
   context = {'citas': citas, 'pacientes': pacientes}
   return render(request, 'nucleo/cita/historicoM.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(medico, name='dispatch')
class filterPaciente(ListView):
   model = Cita
   template_name = 'nucleo/cita/historicoM.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      paciente = self.request.GET.get('paciente', None)
      pacientes = Usuario.objects.filter(id__in=paciente)
      if paciente != '0':
         citas = Cita.objects.filter(idMedico=self.request.user.id, idPaciente=paciente, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      else:
         citas = Cita.objects.filter(idMedico=self.request.user.id, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
         pacientes = Usuario.objects.filter(id__in=citas.values_list('idPaciente', flat=True).distinct())
      context['citas'] = citas
      context['pacientes'] = pacientes
      return context

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class createCompra(CreateView):
   model = Compra
   form_class = compraForm
   template_name = 'nucleo/compra/create.html'
   success_url = reverse_lazy('nucleo:pedirCompra')
   medicamentos = Medicamento.objects.all()
   
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['medicamentos'] = self.medicamentos
      return context

   def post(self, request, *args, **kwargs):
      self.object = self.get_object
      form = self.form_class(request.POST)
      if form.is_valid():
         compra = form.save(commit=False)
         compra.idPaciente = self.request.user
         compra.save()
         messages.success(request, 'Compra creada correctamente')
         return HttpResponseRedirect(reverse('nucleo:pedirCompra'))
      else:
         return self.render_to_response(self.get_context_data(form=form))
   
   def addMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.agregar(medicamento)
      return redirect('nucleo:pedirCompra')

   def removeMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.eliminar(medicamento=medicamento)
      return redirect('nucleo:pedirCompra')

   def restarMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.restar(medicamento=medicamento)
      return redirect('nucleo:pedirCompra')

   def limpiarCarrito(request):
      carrito = Carrito(request)
      carrito.limpiar()
      return redirect('nucleo:pedirCompra')

class loginAPI(APIView):
   def get(self, request, format=None):
      return Response({'detail':'GET Response'})

   def post(self, request, format=None):
      try:
         data=request.data
      except ParseError as error:
         return Response(
            'INVALID JSON - {0}'.format(error.detail),
            status=status.HTTP_400_BAD_REQUEST
         )
      if "user" not in data or "password" not in data:
         return Response(
            'Credenciales incorrectas',
            status=status.HTTP_401_UNAUTHORIZED
         )
      
      user = Usuario.objects.get(username=data["user"])

      if not user:
         return Response(
            'Usuario no encontrado',
            status=status.HTTP_404_NOT_FOUND
         )
      if user.is_paciente == False or user.is_active == False:
         return Response(
            'Usuario no autorizado',
            status=status.HTTP_404_NOT_FOUND
         )
      if check_password(data["password"], user.password)==False:
         return Response(
            'Credenciales incorrectas',
            status=status.HTTP_404_NOT_FOUND
         )

segprivado/nucleo/templates/index.html
{%load static%}

<!DOCTYPE html>
<html lang="en">
    <head>
        <meta charset="utf-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no" />
        <meta name="description" content="" />
        <meta name="author" content="" />
        <title>SEGURIDAD PRIVADA DAM</title>
        <!-- Favicon-->
        <link rel="icon" type="image/x-icon" href="{%static 'assets/favicon.ico'%}" />
        <!-- Font Awesome icons (free version)-->
        <script src="https://use.fontawesome.com/releases/v5.15.4/js/all.js" crossorigin="anonymous"></script>
        <!-- Google fonts-->
        <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css" />
        <link href="https://fonts.googleapis.com/css?family=Lato:400,700,400italic,700italic" rel="stylesheet" type="text/css" />
        <!-- Core theme CSS (includes Bootstrap)-->
        <link href="{%static 'css/styles.css'%}" rel="stylesheet" />
    </head>
    <body id="page-top">
        <!-- Navigation-->
        <nav class="navbar navbar-expand-lg bg-secondary text-uppercase fixed-top" id="mainNav">
            <div class="container">
   
                    <a class="carousel-control-prev-icon" href="{% url 'nucleo:home' %}"></a>
        
               
                <a class="navbar-brand" >SEGURIDAD PRIVADA DAM</a>
                <button class="navbar-toggler text-uppercase font-weight-bold bg-primary text-white rounded" type="button" data-bs-toggle="collapse" data-bs-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">
                    Menu
                    <i class="fas fa-bars"></i>
                </button>
                <div class="collapse navbar-collapse" id="navbarResponsive">
                    <ul class="navbar-nav ms-auto">
                        {% if request.user.is_staff %}
                        <img src="{%static 'users/ADMIN.jpg'%}" alt="mdo" width="55" height="55" class="rounded-circle">  <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded">{{ user.username }}</a></li>
                        {%endif%}
                        {% if  request.user.is_paciente %}
                        <img src="{%static 'users/ADMIN.jpg'%}" alt="mdo" width="55" height="55" class="rounded-circle">  <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded">{{ user.username }}</a></li>
                        {% endif %}
                        {% if  request.user.is_medico %}
                        <img src="{%static 'users/ADMIN.jpg'%}" alt="mdo" width="55" height="55" class="rounded-circle">  <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded">{{ user.username }}</a></li> 
                        {%endif%}
                        
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" href="{% url 'viewProfile' %}">Profile</a></li>
                        <li class="nav-item mx-0 mx-lg-1"><a class="nav-link py-3 px-0 px-lg-3 rounded" onclick="return confirm('¿Está seguro que desea hacer logout?')" href="{% url 'logout' %}">Logout</a></li>
                        
                    </ul>
                </div>
            </div>
        </nav>
        <!-- Masthead-->
        <header class="masthead bg-primary text-white text-center">
            {%block content%}

            {%endblock content%}
        </header>
        <!-- Portfolio Section-->
        
        <!-- About Section-->
        
        <!-- Contact Section-->
        
        <!-- Footer-->
        <footer class="footer text-center">
            <div class="container">
                <div class="row">
                    <!-- Footer Social Icons-->
                    
                    <!-- Footer About Text-->
                    <div class="col-lg-4 mb-5 mb-lg-0">
                        <h4 class="text-uppercase mb-4">Consulta nuestros medicos</h4>
                        <a class="btn btn-outline-light" href="{% url 'nucleo:especialidad' %}">-></a>
                    </div>
                    <div class="col-lg-4">
                        <h4 class="text-uppercase mb-4">Sobre Segprivado</h4>
                        <p class="lead mb-0">
                            Una web para la gestion de los datos de nuestros pacientes y medicos de forma segura y confidencial.
                        </p>
                    </div>
                </div>
            </div>
        </footer>
        <!-- Copyright Section-->
        
        <!-- Portfolio Modals-->
        <!-- Portfolio Modal 1-->
        
        
        <!-- Bootstrap core JS-->
        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/js/bootstrap.bundle.min.js"></script>
        <!-- Core theme JS-->
        <script src="{%static 'js/scripts.js'%}"></script>
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <!-- * *                               SB Forms JS                               * *-->
        <!-- * * Activate your form at https://startbootstrap.com/solution/contact-forms * *-->
        <!-- * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * * *-->
        <script src="https://cdn.startbootstrap.com/sb-forms-latest.js"></script>
    </body>
</html>