segprivado/nucleo/urls.py
from django.urls import path
from nucleo import views

app_name = "nucleo"

urlpatterns = [
    
    path('home', views.home, name= "home"),

    path('medicamento/', views.medicamento, name="indexMedicamento"),
    path('medicamento/create/', views.medicamentoCreate.as_view(), name="crearMedicamento"),
    path('medicamento/update/<int:pk>/', views.medicamentoUpdate.as_view(), name="actualizarMedicamento"),
    path('medicamento/delete/<int:pk>/', views.medicamentoDelete, name="eliminarMedicamento"),

    path('especialidad/', views.medicosEspecilidad.as_view(), name="especialidad"),

    path('cita/', views.createCita.as_view(), name="pedirCita"),
    path('cita/indexM/', views.citasActual, name="indexMCita"),
    path('cita/update/<int:pk>/', views.citaTratamiento.as_view(), name="actualizarCita"),
    path('cita/index/', views.verCitas, name="indexCita"),
    path('cita/filter/', views.citasFilter.as_view(), name="filterCita"),
    path('cita/historialM/', views.verCitasMedico, name="historialMCita"),
    path('cita/filterP/', views.filterPaciente.as_view(), name="filterPaciente"),

    path('compra/', views.createCompra.as_view(), name="pedirCompra"),
    path('compra/add/<int:pk>/', views.createCompra.addMedicamento, name="addMedicamento"),

    path('api/login/', views.loginAPI.as_view(), name="loginAPI"),
    path('api/medicos/', views.medicos_APIView.as_view(), name="medicosAPI"),
    path('api/citas/', views.historialCitas_APIView.as_view(), name="citasAPI"),
]

segprivado/segprivado/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from registration.views import Login, LogoutView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', Login.as_view(), name='login'),
    path('',include('nucleo.urls')),
    path('logout', LogoutView.as_view(), name='logout'),
    path('home', TemplateView.as_view(template_name='nucleo/home.html'), name='home'),
    path('acounts/', include('registration.urls')),
]

segprivado/nucleo/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.
class Usuario(AbstractUser):
    MedicodeFamilia= 'MF'
    Digestivo= 'DG'
    Neurologo= 'NE'
    Dermatologo= 'DT'
    Traumatologo= 'TR'
    SinEspecialidad= 'SE'
    ESPECIALIDAD_CHOICES = [(MedicodeFamilia, 'Medico de Familia'),(Digestivo, 'Digestivo'),(Neurologo, 'Neurologo'),(Dermatologo, 'Dermatologo'),(Traumatologo, 'Traumatologo'),(SinEspecialidad, 'Sin Especialidad')]
    first_name = models.CharField(max_length=30, verbose_name="Nombre", null=True)
    last_name = models.CharField(max_length=30, verbose_name="Apellidos", null=True)
    edad = models.IntegerField(null=True)
    date_joined = models.DateTimeField(verbose_name="Fecha de alta", null=True)
    especialidad = models.CharField(max_length=2, choices=ESPECIALIDAD_CHOICES, default=SinEspecialidad)
    username = models.CharField(max_length=30, unique=True, verbose_name="Usuario", null=True)
    password = models.CharField(max_length=100, verbose_name="Contraseña", null=True)
    is_active = models.BooleanField(verbose_name="Activo", default=False)
    is_paciente = models.BooleanField('paciente status',null=True)
    is_medico = models.BooleanField('medico status',null=True)
    direccion = models.CharField(max_length=100, null=True)
    foto = models.ImageField(upload_to='fotos/', null=True)

    def __str__(self):
        if self.first_name is not None or self.last_name is not None:
            return self.first_name + " " + self.last_name
        return self.username
    
    
class Cita(models.Model):
    fecha = models.DateField(null=True)
    observaciones = models.TextField(max_length=200, null=True)
    idMedico = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='medico')
    idPaciente = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True, related_name='paciente')
    
    class Meta:
        ordering = ('fecha',)

class Medicamento(models.Model):
    nombre = models.CharField(max_length=30, null=True)
    descripcion = models.TextField(max_length=100, null=True)
    receta = models.CharField(max_length=1, null=True)
    precio = models.FloatField(null=True)
    stock = models.IntegerField(null=True)
    
class Compra(models.Model):
    fecha = models.DateField(null=True)
    idPaciente = models.ForeignKey(Usuario, on_delete=models.CASCADE, null=True)
    precio = models.FloatField(null=True)
    
class Compra_medicamento(models.Model):
    idCompra = models.ForeignKey(Compra, on_delete=models.CASCADE, null=True)
    idMedicamento = models.ForeignKey(Medicamento, on_delete=models.CASCADE, null=True)
    cant = models.IntegerField(null=True)

segprivado/nucleo/forms.py
from cProfile import label
from datetime import datetime
from faulthandler import disable
from nucleo.models import *
from django import forms

class medicamentoForm(forms.ModelForm):
    class Meta:
        model = Medicamento
        fields = ['nombre', 'descripcion', 'receta', 'precio', 'stock']
        labels = {'nombre':'Nombre', 'descripcion':'Descripcion', 'receta':'Receta', 'precio':'Precio', 'stock':'Stock'}
        widgets = {
            'nombre': forms.TextInput(attrs={'class':'form-control'}), 
            'descripcion': forms.Textarea(attrs={'class':'form-control'}), 
            'receta': forms.TextInput(attrs={'class':'form-control'}), 
            'precio': forms.NumberInput(attrs={'class':'form-control'}), 
            'stock': forms.NumberInput(attrs={'class':'form-control'})
            }

class citaForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(citaForm, self).__init__(*args, **kwargs)
        self.fields['idMedico'].queryset = Usuario.objects.filter(is_medico=True)
        
    class Meta:
        model = Cita
        fields = ['fecha', 'idMedico',]
        labels = {'fecha':'Fecha', 'idMedico':'Medico'}
        
        
        widgets = { 
            'fecha': forms.DateInput(attrs={'type':'date'}),
            
        }

    def clean_fecha(self):
        fecha = self.cleaned_data['fecha']
        if fecha < datetime.date(datetime.now()):
            raise forms.ValidationError("La fecha debe ser mayor o igual a la actual")
        return fecha

    def clean_dis(self):
        fecha = self.cleaned_data['fecha']
        idMedico = self.cleaned_data['idMedico']
        if Cita.objects.filter(fecha=fecha, idMedico=idMedico).count() > 3:
            raise forms.ValidationError("Ese medico no esta disponible en esa fecha")
        return fecha

class citaFormTratamiento(forms.ModelForm):
    class Meta:
        model = Cita
        fields = ['observaciones',]
        labels = {'observaciones':'Observaciones'}
        widgets = { 
            'observaciones': forms.Textarea(attrs={'class':'form-control'}),
            
        }

class compraForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super(compraForm, self).__init__(*args, **kwargs)
        

    class Meta:
        model = Compra
        fields = ['fecha','precio']
        labels = {'fecha':'Fecha', 'idPaciente':'Paciente', 'precio':'Total'}
        widgets = {
            'fecha': forms.DateInput(attrs={
                'disabled': True,
                'value':datetime.date(datetime.now())
                }),
            'precio': forms.NumberInput(attrs={
                'disabled': True,
                'value':0.0}),
        }

segprivado/nucleo/views.py
from django.http import HttpResponseRedirect
from django.shortcuts import get_object_or_404, redirect, render
from django.urls import reverse_lazy, reverse
from nucleo.models import Usuario
from nucleo.forms import *
from django.views.generic import CreateView, UpdateView, ListView
from django.contrib import messages
from django.contrib.auth.hashers import check_password
from django.utils.decorators import method_decorator
from django.contrib.admin.views.decorators import staff_member_required
from django.contrib.auth.decorators import login_required
from nucleo.decorators import *
from nucleo.serializers import citaSerializer, medicoSerializer
from .carrito import Carrito

from rest_framework.views import APIView
from rest_framework.response import Response
from rest_framework.exceptions import ParseError
from rest_framework import serializers, status
from rest_framework.authtoken.models import Token
from rest_framework.permissions import IsAuthenticated
# Create your views here.

@login_required
def home(request):
    medico=Usuario.objects.filter(is_medico=True)
    
    
    context={'medicos':medico,
 }
    return render(request, 'nucleo/home.html')

@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class medicamentoCreate(CreateView):
      model = Medicamento
      form_class = medicamentoForm
      template_name = 'nucleo/medicamentos/create.html'
      success_url = reverse_lazy('nucleo:indexMedicamento')

      def post(self, request, *args, **kwargs):
         self.object = self.get_object
         form = self.form_class(request.POST)
         if form.is_valid():
            medicamento = form.save(commit=False)
            medicamento.save()
            messages.success(request, 'Medicamento creado correctamente')
            return HttpResponseRedirect(reverse('nucleo:indexMedicamento'))
         else:
            return self.render_to_response(self.get_context_data(form=form))

@method_decorator(login_required, name='dispatch')
@method_decorator(staff_member_required, name='dispatch')
class medicamentoUpdate(UpdateView):
      model = Medicamento
      form_class = medicamentoForm
      template_name = 'nucleo/medicamentos/create.html'
      success_url = reverse_lazy('nucleo:indexMedicamento')

@login_required
@staff_member_required
def medicamentoDelete(request, pk):
   medicamento = get_object_or_404(Medicamento, id=pk)
   medicamento.delete()
   messages.success(request, 'Medicamento eliminado correctamente')
   return redirect('nucleo:indexMedicamento')

@login_required
@staff_member_required
def medicamento(request):
   medicamentos = Medicamento.objects.all()
   context = {'medicamentos': medicamentos}
   return render(request, 'nucleo/medicamentos/index.html', context)

class medicosEspecilidad(ListView):
   model = Usuario
   template_name = 'nucleo/especialidad.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      especialidadGet = self.request.GET.get('especialidad')
      
      if(self.request.GET.get('especialidad')!=0):
         data = Usuario.objects.filter(especialidad=especialidadGet, is_medico=True)
      else:
         data = Usuario.objects.filter(is_medico=True)
      
      context['data'] = data
      return context

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class createCita(CreateView):
   model = Cita
   form_class = citaForm
   template_name = 'nucleo/cita/create.html'
   success_url = reverse_lazy('nucleo:home')

   def post(self, request, *args, **kwargs):
      self.object = self.get_object
      form = self.form_class(request.POST)
      if form.is_valid():
         cita = form.save(commit=False)
         cita.idPaciente = self.request.user
         cita.idMedico = form.cleaned_data['idMedico']
         cita.save()
         messages.success(request, 'Cita creada correctamente')
         return HttpResponseRedirect(reverse('nucleo:home'))
      else:
         return self.render_to_response(self.get_context_data(form=form))
   
   def dispatch(self, request, *args, **kwargs):
         return super().dispatch(request, *args, **kwargs)

@login_required
@medico
def citasActual(request):
   citas = Cita.objects.filter(fecha__gte=datetime.date(datetime.now()), idMedico=request.user.id)
   context = {'citas': citas}
   return render(request, 'nucleo/cita/indexM.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(medico, name='dispatch')
class citaTratamiento(UpdateView):
   model = Cita
   form_class = citaFormTratamiento
   template_name = 'nucleo/cita/update.html'
   success_url = reverse_lazy('nucleo:actualizarCita')

@login_required
@paciente
def verCitas(request):
   if(request.user.is_paciente):
      citas = Cita.objects.filter(idPaciente=request.user.id)
   context = {'citas': citas}
   return render(request, 'nucleo/cita/indexP.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class citasFilter(ListView):
   model = Cita
   template_name = 'nucleo/cita/indexP.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      fechaIni = self.request.GET.get('fechaIni', None)
      fechaFin = self.request.GET.get('fechaFin', None)
      if fechaIni != '' and fechaFin != '':
         citas = Cita.objects.filter(idPaciente=self.request.user.id, fecha__range=(fechaIni, fechaFin)).filter(fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      else:
         citas = Cita.objects.filter(idPaciente=self.request.user.id).filter(fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      context['citas'] = citas
      return context

@login_required
@medico
def verCitasMedico(request):
   if(request.user.is_medico):
      citas = Cita.objects.filter(idMedico=request.user.id, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      paciente = citas.values_list('idPaciente', flat=True).distinct()
      pacientes = Usuario.objects.filter(id__in=paciente)
   context = {'citas': citas, 'pacientes': pacientes}
   return render(request, 'nucleo/cita/historicoM.html', context)

@method_decorator(login_required, name='dispatch')
@method_decorator(medico, name='dispatch')
class filterPaciente(ListView):
   model = Cita
   template_name = 'nucleo/cita/historicoM.html'

   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      paciente = self.request.GET.get('paciente', None)
      pacientes = Usuario.objects.filter(id__in=paciente)
      if paciente != '0':
         citas = Cita.objects.filter(idMedico=self.request.user.id, idPaciente=paciente, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
      else:
         citas = Cita.objects.filter(idMedico=self.request.user.id, fecha__lte=datetime.date(datetime.now())).order_by('fecha')
         pacientes = Usuario.objects.filter(id__in=citas.values_list('idPaciente', flat=True).distinct())
      context['citas'] = citas
      context['pacientes'] = pacientes
      return context

@method_decorator(login_required, name='dispatch')
@method_decorator(paciente, name='dispatch')
class createCompra(CreateView):
   model = Compra
   form_class = compraForm
   template_name = 'nucleo/compra/create.html'
   success_url = reverse_lazy('nucleo:pedirCompra')
   medicamentos = Medicamento.objects.all()
   
   def get_context_data(self, **kwargs):
      context = super().get_context_data(**kwargs)
      context['medicamentos'] = self.medicamentos
      return context

   def post(self, request, *args, **kwargs):
      self.object = self.get_object
      form = self.form_class(request.POST)
      if form.is_valid():
         compra = form.save(commit=False)
         compra.idPaciente = self.request.user
         compra.save()
         messages.success(request, 'Compra creada correctamente')
         return HttpResponseRedirect(reverse('nucleo:pedirCompra'))
      else:
         return self.render_to_response(self.get_context_data(form=form))
   
   def addMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.agregar(medicamento)
      return redirect('nucleo:pedirCompra')

   def removeMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.eliminar(medicamento=medicamento)
      return redirect('nucleo:pedirCompra')

   def restarMedicamento(request,pk):
      carrito = Carrito(request)
      medicamento = Medicamento.objects.get(id=pk)
      carrito.restar(medicamento=medicamento)
      return redirect('nucleo:pedirCompra')

   def limpiarCarrito(request):
      carrito = Carrito(request)
      carrito.limpiar()
      return redirect('nucleo:pedirCompra')

class loginAPI(APIView):
   def get(self, request, format=None):
      return Response({'detail':'GET Response'})

   def post(self, request, format=None):
      try:
         data=request.data
      except ParseError as error:
         return Response(
            'INVALID JSON - {0}'.format(error.detail),
            status=status.HTTP_400_BAD_REQUEST
         )
      if "user" not in data or "password" not in data:
         return Response(
            'Credenciales incorrectas',
            status=status.HTTP_401_UNAUTHORIZED
         )
      
      user = Usuario.objects.get(username=data["user"])

      if not user:
         return Response(
            'Usuario no encontrado',
            status=status.HTTP_404_NOT_FOUND
         )
      if user.is_paciente == False or user.is_active == False:
         return Response(
            'Usuario no autorizado',
            status=status.HTTP_404_NOT_FOUND
         )
      if check_password(data["password"], user.password)==False:
         return Response(
            'Credenciales incorrectas',
            status=status.HTTP_404_NOT_FOUND
         )

segprivado/nucleo/templates/nucleo/cita/create.html
{% extends 'index.html' %}
{% block titulo %} Pedir Cita {% endblock %}

{%block content %}
<h1 class="text-secondary">Pedir Cita</h1>
<style>
    form {
        width: 60%;
        margin:auto;
    }
</style>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    
    {{ form.as_p }}
    
    <button type="submit" class="btn btn-secondary">Guardar</button>
</form>

{%endblock content%}

segprivado/nucleo/templates/nucleo/cita/historicoM.html
{% extends 'index.html' %}
{% block titulo %} Citas {% endblock %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{%block content %}
<h1 class="text-secondary">Historico de Citas</h1>
<br />
<nav class="navbar">
    <form class="container-fluid" action="{% url 'nucleo:filterPaciente'%}">
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">Paciente: </span>
            <select class="form-select" aria-label="Default select example" name="paciente">
                <option value="0">Todos</option>
                {% for p in pacientes %}
                <option value="{{ p.id }}">{{ p.first_name }} {{ p.last_name }}</option>
                {% endfor %}
            </select>
            
            <button type="submit" class="btn btn-secondary">Buscar</button>
        </div>
    </form>
</nav>
{% if citas %}
<table class="table">
    <thead class="table-primary">
        <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Observaciones</th>
            <th scope="col">Paciente</th>
        </tr>
    </thead>
    <tbody class="table-secondary">
        {% for cita in citas %}
        <tr>
            <td>{{ cita.fecha }}</td>
            <td>{{ cita.observaciones }}</td>
            <td>{{ cita.idPaciente }}</td>
        </tr>
        {% endfor %}
    </tbody>
{% else %}  
    <h1>No hay citas registradas</h1>
{% endif %}
</table>
{% endblock content %}

segprivado/nucleo/templates/nucleo/cita/indexM.html
{% extends 'index.html' %}
<link rel="stylesheet" src="static.css">
{% block titulo %} Citas {% endblock %}

{%block content %}
<h1>Citas</h1>
 
<br>
</br>

<br>
</br>
{% if citas %}
<table class="table">
  <thead class="table-primary">
    <tr>
      <th scope="col">Fecha</th>
      <th scope="col">Paciente</th>
      <th scope="col">Observaciones</th>
      <th scope="col">Acciones</th>
    </tr>
  </thead>
  <tbody class="table-secondary">
    {% for c in citas %}
    <tr>
      <td>{{ c.fecha }}</td>
      <td>{{ c.idPaciente }}</td>
      <td>{{ c.observaciones }}</td>
      <td>
        <a class="btn btn-secondary" href="{%url 'nucleo:actualizarCita' pk=c.id %}">Tratamiento</a>
        
      </td>
    </tr>
    {% endfor %}

    {% else %}
    <h1>No hay citas registradas</h1>

    {% endif %}
  </tbody>
</table>

{% endblock content%}

segprivado/nucleo/templates/nucleo/cita/indexP.html
{% extends 'index.html' %}
{% block titulo %} Citas {% endblock %}
<ul class="messages">
  {% for message in messages %}
  <li{% if message.tags %} class="{{ message.tags }}"{% endif %}>{{ message }}</li>
  {% endfor %}
</ul>
{%block content %}
<h1 class="text-secondary">Historico de Citas</h1>
<br />
<nav class="navbar">
    <form class="container-fluid" action="{% url 'nucleo:filterCita'%}">
        <div class="input-group">
            <span class="input-group-text" id="basic-addon1">Filtros: </span>
            <span class="input-group-text" id="basic-addon1">Fecha de Inicio: </span>
            <input type="date" class="form-control" name="fechaIni">
            <span class="input-group-text" id="basic-addon1">Fecha Final: </span>
            <input type="date" class="form-control" name="fechaFin">
            <button type="submit" class="btn btn-secondary">Buscar</button>
        </div>
    </form>
</nav>
<br />
{% if citas %}
<table class="table">
    <thead class="table-primary">
        <tr>
            <th scope="col">Fecha</th>
            <th scope="col">Observaciones</th>
            <th scope="col">Medico</th>
    </thead>
    <tbody class="table-secondary">
        {% for cita in citas %}
        <tr>
            <td>{{ cita.fecha }}</td>
            <td>{{ cita.observaciones }}</td>
            <td>{{ cita.idMedico }}</td>
        </tr>
        {% endfor %}
    </tbody>
{% else %}  
    <h1>No hay citas registradas</h1>
{% endif %}
</table>
{% endblock content %}

segprivado/nucleo/templates/nucleo/cita/update.html
{% extends 'index.html' %}
{% block titulo %} Tratamiento {% endblock %}

{%block content %}
<h1 class="text-secondary">Tratamiento</h1>
<style>
    form {
        width: 60%;
        margin:auto;
    }
</style>
{% if messages %}
    <div class="alert alert-success">
        {% for message in messages %}
            {{ message }}
        {% endfor %}
    </div>
{% endif %}
<form method="post" enctype="multipart/form-data">
    {% csrf_token %}
    
    
    {{ form.as_p }}
    
    <button type="submit" class="btn btn-secondary">Guardar</button>
</form>

{%endblock content%}